---

name: Deploy Epic Duel

on:
  push:
    branches:
      - main

jobs:
  deploy-epicduel:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: sync to s3
        run: |
          echo "S3 Bucket"
          aws s3 sync ./ s3://epicduel.starwarsccg.org/ --exclude '.git/*' --exclude '.github/*' --exclude 'node_modules/*' --exclude README.md --exclude package-lock.json --exclude package.json --exclude epicduel_banner.png --exclude epicduel_banner.xcf --exclude favicon.xcf
          echo "Cloudfront Invalidation"
          aws cloudfront create-invalidation --distribution-id E7I5ZFY1IJWEX --paths "/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}






